/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Festival = IDL.Record({
  'id' : IDL.Nat,
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'nameOdia' : IDL.Text,
  'description' : IDL.Text,
  'nameEnglish' : IDL.Text,
});
export const TithiEvent = IDL.Record({
  'tithi' : IDL.Text,
  'lunarMonth' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFestival' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addTithiEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteFestival' : IDL.Func([IDL.Nat], [], []),
  'getAllFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
  'getAllTithiEvents' : IDL.Func([], [IDL.Vec(TithiEvent)], ['query']),
  'getFestivalsByDateRange' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(Festival)],
      ['query'],
    ),
  'getFestivalsByMonth' : IDL.Func([IDL.Nat], [IDL.Vec(Festival)], ['query']),
  'updateFestival' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Festival = IDL.Record({
    'id' : IDL.Nat,
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'nameOdia' : IDL.Text,
    'description' : IDL.Text,
    'nameEnglish' : IDL.Text,
  });
  const TithiEvent = IDL.Record({
    'tithi' : IDL.Text,
    'lunarMonth' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addFestival' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addTithiEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteFestival' : IDL.Func([IDL.Nat], [], []),
    'getAllFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
    'getAllTithiEvents' : IDL.Func([], [IDL.Vec(TithiEvent)], ['query']),
    'getFestivalsByDateRange' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(Festival)],
        ['query'],
      ),
    'getFestivalsByMonth' : IDL.Func([IDL.Nat], [IDL.Vec(Festival)], ['query']),
    'updateFestival' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };